[project]
name = "llm-data-aug"
version = "0.1.0"
description = "Comparative study of Resampling and LLM for data augmentation for sentiment analysis tasks."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
